config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :locations, only: [:show, :index, :create, :new]
  resources :users, only: [:show, :create, :new]

  get '' => redirect('/home')
  get 'welcome', to: 'sessions#welcome'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  scope '/tests' do
    get '', to: 'covid_tests#index'

    get 'positive', to: 'covid_tests#new_positive'
    get 'negative', to: 'covid_tests#new_negative'

    post 'positive', to: 'covid_tests#create_positive'
    post 'negative', to: 'covid_tests#create_negative'
  end

  get 'home', to: 'home#index'

  get 'qr/checkin', to: 'user_locations#new_checkin'
  get 'qr/checkout', to: 'user_locations#new_checkout'
  delete 'user_location', to: 'user_locations#destroy'

  post 'checkin/:id', to: 'external_user_locations#check_in'
  post 'checkout/:id', to: 'external_user_locations#check_out'

  post 'contagion/new', to: 'external_contagion#create'

  resources :user_locations, only: :create

  get 'location/:id', to: 'locations#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user_decorator = UserDecorator.new(current_user)
    return admin_home if current_user.admin?

    @user_decorator.current_location.update_concurrence if @user_decorator.at_location?
    @location_decorator = LocationDecorator.new(@user_decorator.current_location) if @user_decorator.at_location?
    @notifications = current_user.user_notifications
    @notifications.each(&:destroy)
  end

  private

  def admin_home
    @locations = Location.all
    @locations_by_capacity = Location.group(:capacity).count
    @users_by_state = User.group(:state).count
    render 'admin_index'
  end
end

app/views/home/admin_index.html.erb
<h1>
  Hola administrador <%= @user_decorator.name %>!
</h1>
<script defer
  src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.secrets.google_api_key%>&callback=initMap">
</script>

<%= javascript_tag do %>
window.locations = <%= raw @locations.to_json %>;
<% end %>

<script src='assets/admin_map.js'></script>

<div id="google-maps-api-map" style="width: 1110px; height: 500px"></div>

<div class="container p-3 my-3 border">
  <div class="row">
    <div class="col">
    <h1>Usuarios</h1><br>
    <h3>Cantidad de usuarios: <%= @users_by_state.values.sum %> </h3> <br>
    <h4> Sanos: <%= @users_by_state['healthy'] || 0 %></h4> 
    <h4> En Riesgo: <%= @users_by_state['at_risk'] || 0 %></h4> 
    <h4> Infectados: <%= @users_by_state['infected'] || 0 %></h4> 
    </div>
    <div class="col">
      <%= pie_chart @users_by_state, library: {pieSliceText:
  'value-and-percentage'} %>
    </div>
  </div>
</div>

<div class="container p-3 my-3 border">
  <div class="row">
    <div class="col">
    <h1>Locaciones</h1><br>
    <h3>Cantidad de locaciones: <%= @locations.count %></h3> <br>
    </div>
    <div class="col">
      <%= column_chart @locations_by_capacity, xtitle: "Capacidad", ytitle: "Cantidad" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>
  Hola <%= @user_decorator.name %>!
</h1>

<h4>
  Usted está <%= @user_decorator.state_description %>.
</h4><br>

<% if @user_decorator.at_location? %>
<h4>
  Usted está en <%= @location_decorator.name %>. Hay <%= @location_decorator.concurrence %>
  persona<%= 's' if @location_decorator.has_many_users? %> en la locación y la capacidad máxima es
  <%= @location_decorator.capacity %>.
</h4>
<% end %>

<div class="row mx-md-n5">
  <div class="col px-md-5">
    <% if @user_decorator.can_check_in? %>
    <%= button_to 'Entrar con QR', '/qr/checkin', method: 'get', class: "btn btn-outline-dark btn-lg" %>
    <% end %>
    <% if @user_decorator.can_check_out? %>
    <%= button_to 'Salir con QR', '/qr/checkout', method: 'get', class: "btn btn-outline-dark btn-lg" %>
    <% end %>
  </div>
  <div class="col px-md-5">
    <% if @user_decorator.can_get_infected? %>
    <%= button_to 'Registrar test positivo', '/tests/positive', method: 'get', class: "btn btn-outline-danger btn-lg" %>
    <% end %>
  </div>
</div>
<br>
<div class="row mx-md-n5">
  <div class="col px-md-5">
    <%= button_to 'Registrar nueva locación', new_location_path, method: 'get',class: "btn btn-outline-dark btn-lg" %>
  </div>
  <div class="col px-md-5">
    <%= button_to 'Registrar test negativo', '/tests/negative', method: 'get', class: "btn btn-outline-success btn-lg" %>
  </div>
</div>
<br>

<div style="position: absolute; top: 40px; right: 20px;">
<% @notifications.each do | notification | %>
  <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" >
    <div class="toast-header">
      <%= image_tag "logo.png", width: "20", height: "25", class: "rounded mr-2"%>
      <!--<img src="/assets/logo.png" class="rounded mr-2" height="25" width="20">-->
      <strong class="mr-auto">Notificación</strong>
      <small><%= notification.created_at %></small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close" >
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      <%= notification.message %>
    </div>
  </div>
<% end %>
</div>

<script>
  $('.toast').toast({
    autohide: false
  })
  $('.toast').toast('show')
  
</script>