config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :locations, only: [:show, :index, :create, :new]
  resources :users, only: [:show, :create, :new]

  get '' => redirect('/home')
  get 'welcome', to: 'sessions#welcome'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  scope '/tests' do
    get '', to: 'covid_tests#index'

    get 'positive', to: 'covid_tests#new_positive'
    get 'negative', to: 'covid_tests#new_negative'

    post 'positive', to: 'covid_tests#create_positive'
    post 'negative', to: 'covid_tests#create_negative'
  end

  get 'home', to: 'home#index'

  get 'qr/checkin', to: 'user_locations#new_checkin'
  get 'qr/checkout', to: 'user_locations#new_checkout'
  delete 'user_location', to: 'user_locations#destroy'

  post 'checkin/:id', to: 'external_user_locations#check_in'
  post 'checkout/:id', to: 'external_user_locations#check_out'

  post 'contagion/new', to: 'external_contagion#create'

  resources :user_locations, only: :create

  get 'location/:id', to: 'locations#show'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Yo Estuve Aqui</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<nav class="navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="/home">
    <%= image_tag "logo.png", width: "20", height: "30", class: "d-inline-block align-top", alt: "", loading: "lazy"%>
    <!--<img src="/assets/logo.png" width="20" height="30" class="d-inline-block align-top" alt="" loading="lazy">-->
    YEA!
  </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to "Salir", '/logout', method: 'delete', class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>



<body>
  <div class='container'>
    <br>
    <%= yield %>
  </div>
</body>

<% flash.each do |type, message| %>
<div class="alert alert-info">
  <%= message %>
</div>
<% end %>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Yo Estuve Aqui</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<nav class="navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="/home">
    <%= image_tag "logo.png", width: "20", height: "30", class: "d-inline-block align-top", alt: "", loading: "lazy"%>
    <!--<img src="/assets/logo.png" width="20" height="30" class="d-inline-block align-top" alt="" loading="lazy">-->
    YEA!
  </a>
  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <li><%= link_to "Home", '/home', class: 'nav-link' %></li>
      </li>
      <li class="nav-item">
        <%= link_to "Mis locaciones", locations_path, method: 'get', class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Mis tests", '/tests', method: 'get', class: 'nav-link' %>
      </li>
    </ul>
    </div>
    <ul class="nav navbar-nav navbar-right" >
      <li class="nav-item">
        <%= link_to "Salir", '/logout', method: 'delete', class: 'nav-link' %>
      </li>
    </ul>
    
</nav>


<body>
  <div class='container'>
    <br>
    <%= yield %>
  </div>
</body>

<% flash.each do |type, message| %>
<div class="alert alert-info">
  <%= message %>
</div>
<% end %>

</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Yo Estuve Ahí</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/home">
      <%= image_tag "logo.png", width: "20", height: "30", class: "d-inline-block align-top", alt: "", loading: "lazy"%>
      <!--<img src="/assets/logo.png" width="20" height="30" class="d-inline-block align-top" alt="" loading="lazy">-->
      YEA!
    </a>
    <form class="form-inline">
      <%= link_to "Ingresá", '/login', method: 'get', class: 'btn btn-outline-light' %>
      <div style="padding-left: 10px;">
       <%= link_to "Registrate", new_user_path, method: 'get', class: 'btn btn-outline-light' %>
      </div>
    </form>
  </nav>

</head>

<body>
  <%= yield %>
</body>

<% flash.each do |type, message| %>
<div class="alert alert-danger" >
<%= message %>
</div>
<% end %>

</html>